apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gradle
  strategy:
    type: Recreate
  template:
    metadata:
      name: gradle
      labels:
        name: gradle
    spec:
      containers:
        - name:  gradle
          image: gradle:7.0
          args: ["sleep", "infinity"]
          resources:
            limits:
              memory: 1536Mi
            requests:
              memory: 1024Mi
